version: "3"

services:
  nginx:
    image: registry.cn-beijing.aliyuncs.com/renkx/nginx:latest
    container_name: nginx
    hostname: nginx
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${CONF_DIR}:/conf:rw
      - ${CONF_DIR}:/etc/nginx/http.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    network_mode: "host"
#  nginx:
#    build:
#      context: ./services/nginx
#    container_name: nginx
#    hostname: nginx
#    #ports:
#    #  - "${NGINX_HTTP_HOST_PORT}:80"
#    #  - "${NGINX_HTTPS_HOST_PORT}:443"
#    volumes:
#      - ${SOURCE_DIR}:/www/:rw
#      - ${CONF_DIR}:/conf:rw
#      - ${CONF_DIR}:/etc/nginx/http.d/:rw
#      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
#      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
#    restart: always
#    network_mode: "host"

  ag:
    image: registry.cn-beijing.aliyuncs.com/renkx/xray:${AG_VERSION}
    container_name: ag
    hostname: ag
    privileged: true
    restart: always
    volumes:
      - ${CONF_DIR}:/etc/xray/:rw
      - ${AG_LOG_DIR}:/var/log/xray/:rw
    network_mode: "host"

  ad:
    image: adguard/adguardhome:${AD_VERSION}
    container_name: ad
    hostname: ad
    volumes:
      - ${ADGUARDHOME_LOG_DIR}:/opt/adguardhome/work:rw
      - ${CONF_ADGUARDHOME_DIR}:/opt/adguardhome/conf:rw
    restart: always
    network_mode: "host"

  gost:
    image: ginuerzh/gost
    container_name: gost
    hostname: gost
    volumes:
      - ${CONF_DIR}/gost.json:/gost.json
    restart: always
    network_mode: "host"
    command: -C /gost.json

#  smartdns:
#    image: registry.cn-beijing.aliyuncs.com/renkx/smartdns:latest
#    container_name: smartdns
#    hostname: smartdns
#    volumes:
#      - ${CONF_SMARTDNS_DIR}:/etc/smartdns/:rw
#    restart: always
#    network_mode: "host"

#  使用 Dockerfile 生成镜像
#  smartdns:
#    build:
#      context: .
#      dockerfile: ./services/smartdns/Dockerfile
#    container_name: smartdns
#    hostname: smartdns
#    volumes:
#      - ${CONF_SMARTDNS_DIR}:/etc/smartdns/:rw
#    restart: always
#    network_mode: "host"

#  frps:
#    image: ${FRP_IMAGE_VERSION}
#    container_name: frps
#    hostname: frps
#    privileged: true
#    restart: always
#    working_dir: /root
#    volumes:
#      - ${CONF_DIR}/frps.ini:/frps.ini:ro
#    command: /frp/frps -c /frps.ini
#    network_mode: "host"