version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
      args:
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    hostname: nginx
    #ports:
    #  - "${NGINX_HTTP_HOST_PORT}:80"
    #  - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${CONF_DIR}:/conf:rw
      - ${CONF_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
    network_mode: "host"

  ag:
    image: teddysun/xray:${AG_VERSION}
    container_name: ag
    hostname: ag
    privileged: true
    restart: always
    depends_on:
      - nginx
    volumes:
      - ${CONF_DIR}:/etc/xray/:rw
      - ${AG_LOG_DIR}:/var/log/xray/:rw
    network_mode: "host"

  ad:
    image: adguard/adguardhome
    container_name: ad
    hostname: ad
    volumes:
      - ${ADGUARDHOME_LOG_DIR}:/opt/adguardhome/work:rw
      - ${CONF_ADGUARDHOME_DIR}:/opt/adguardhome/conf:rw
    restart: always
    network_mode: "host"

#  smartdns:
#    image: registry.cn-beijing.aliyuncs.com/renkx/smartdns:latest
#    container_name: smartdns
#    hostname: smartdns
#    volumes:
#      - ${CONF_SMARTDNS_DIR}:/etc/smartdns/:rw
#    restart: always
#    network_mode: "host"

#  使用 Dockerfile 生成镜像
#  smartdns:
#    build:
#      context: .
#      dockerfile: ./services/smartdns/Dockerfile
#    container_name: smartdns
#    hostname: smartdns
#    volumes:
#      - ${CONF_SMARTDNS_DIR}:/etc/smartdns/:rw
#    restart: always
#    network_mode: "host"

#  frps:
#    image: ${FRP_IMAGE_VERSION}
#    container_name: frps
#    hostname: frps
#    privileged: true
#    restart: always
#    working_dir: /root
#    volumes:
#      - ${CONF_DIR}/frps.ini:/frps.ini:ro
#    command: /frp/frps -c /frps.ini
#    network_mode: "host"